apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: image-processor-app-hpa
  namespace: openfaas-fn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-processor-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      selectPolicy: Max
      policies:
      - type: Percent
        value: 500
        periodSeconds: 3
      - type: Pods
        value: 5
        periodSeconds: 3
    scaleDown:
      stabilizationWindowSeconds: 5
      selectPolicy: Max
      policies:
      - type: Percent
        value: 100
        periodSeconds: 5
      - type: Pods
        value: 5
        periodSeconds: 5

